/**:
  ros__parameters:
    # Body params
    body_length: 0.213 # Length of the vehicle's body [m]
    body_width: 0.106 # Width of the vehicle's body [m]
    body_height: 0.090 # Height of the vehicle's body [m]
    body_density: 7850.0 # Density of the vehicle's body material, e.g., steel [kg/m^3]

    # Wheel params
    wheel_radius: 0.0325 # Radius of each wheel [m]
    wheel_width: 0.025 # Width of each wheel [m]
    wheel_density: 900.0 # Density of the wheel material, e.g., rubber [kg/m^3]

    # Kinematics and dynamics params
    max_steering_angle: 0.506145 # Maximum steering angle of the vehicle [rad]
    max_steering_angular_velocity: 1.570796 # Maximum steering angular velocity [rad/s]
    max_steering_effort: 1.0 # Maximum steering torque [Nm]
    max_velocity: 0.7 # Maximum wheel velocity [m/s]
    max_effort: 10.0 # Maximum wheel torque [Nm]

    # Lidar params
    lidar_length: 0.0543 # Len, [m]
    lidar_width: 0.047 # Width, [m]
    lidar_height: 0.035 # Height, [m]W, 
    lidar_rotation_speed: 10 # Laser rotation freq [Hz]
    lidar_min_range: 0.03 # [m]
    lidar_max_range: 12.0 # [m]
    lidar_measur_freq: 4500 # [points/s]
    lidar_resolution: 0.8 # [degrees]
    lidar_topic: MS200/scan # Topic for lidar-data


    # IMU params
    imu_topic: /imu/data
    imu_update_rate: 10 # Frekvens på IMU data [Hz]




